
package GUI;

import Clases.Pelicula;
import Clases.Pilas;


public class Cartelera extends javax.swing.JFrame {
    private String tipo;
    private final Pelicula pelicula;
    private final Tarifario_Empleado tarifaEmpleado;
    private final DatosCliente datosCliente;
    private Pilas pila;
    
    public void setPila(Pilas pila) {
        this.pila = pila;
    }

   
    public Cartelera() {
        initComponents();
        
        this.datosCliente = new DatosCliente();
        this.tarifaEmpleado = new Tarifario_Empleado();
        this.pelicula = new Pelicula();
    }
    
    public void iniciar(String tipo){
        this.tipo = tipo;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        System.out.println(pila);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void cartelera(Pelicula pelicula){
        if(this.tipo.equals("cliente")){
            this.datosCliente.setPila(pila);
            this.datosCliente.iniciar(this,pelicula);
        }else if(this.tipo.equals("empleado")){
            this.datosCliente.setPila(pila);
            this.tarifaEmpleado.iniciar(this,pelicula);
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        getPelicula1 = new javax.swing.JButton();
        getPelicula2 = new javax.swing.JButton();
        getPelicula3 = new javax.swing.JButton();
        getPelicula4 = new javax.swing.JButton();
        getPelicula5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARTELERA");

        getPelicula1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cartelera_stich.jpg"))); // NOI18N
        getPelicula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPeliculaLiloStich(evt);
            }
        });

        getPelicula2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cartelera_destino.jpg"))); // NOI18N
        getPelicula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPelicula2DestinoFinal(evt);
            }
        });

        getPelicula3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cartelera_chica.jpg"))); // NOI18N
        getPelicula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPeliculaLaChicaDeLaAguja(evt);
            }
        });

        getPelicula4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cartelera_maincraf.jpg"))); // NOI18N
        getPelicula4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPeliculaMaincraft(evt);
            }
        });

        getPelicula5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cartelera_karate.jpg"))); // NOI18N
        getPelicula5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPeliculaKarateKid(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getPelicula4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(getPelicula2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(getPelicula3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(getPelicula5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getPelicula4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getPelicula2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getPelicula3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(getPelicula5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getPeliculaLiloStich(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPeliculaLiloStich
        //Titulo de la pelicula
        this.pelicula.SeleccionarTituloPelicula(0);
        //Genero de la pelicula
        this.pelicula.SeleccionarGeneroPelicula(0);
        //Duracion de la pelicula
        this.pelicula.SeleccionarDuracionPelicula(0);
        // Dirigir a cartelera (CLIENTE/EMPLEADO)
        this.cartelera(this.pelicula);
    }//GEN-LAST:event_getPeliculaLiloStich

    private void getPelicula2DestinoFinal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPelicula2DestinoFinal
        //Titulo de la pelicula
        this.pelicula.SeleccionarTituloPelicula(1);
        //Genero de la pelicula
        this.pelicula.SeleccionarGeneroPelicula(1);
        //Duracion de la pelicula
        this.pelicula.SeleccionarDuracionPelicula(1);
        // Dirigir a cartelera (CLIENTE/EMPLEADO)
        this.cartelera(this.pelicula);
    }//GEN-LAST:event_getPelicula2DestinoFinal

    private void getPeliculaLaChicaDeLaAguja(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPeliculaLaChicaDeLaAguja
        //Titulo de la pelicula
        this.pelicula.SeleccionarTituloPelicula(2);
        //Genero de la pelicula
        this.pelicula.SeleccionarGeneroPelicula(2);
        //Duracion de la pelicula
        this.pelicula.SeleccionarDuracionPelicula(2);
        // Dirigir a cartelera (CLIENTE/EMPLEADO)
        this.cartelera(this.pelicula);
    }//GEN-LAST:event_getPeliculaLaChicaDeLaAguja

    private void getPeliculaMaincraft(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPeliculaMaincraft
        //Titulo de la pelicula
        this.pelicula.SeleccionarTituloPelicula(3);
        //Genero de la pelicula
        this.pelicula.SeleccionarGeneroPelicula(3);
        //Duracion de la pelicula
        this.pelicula.SeleccionarDuracionPelicula(3);
        // Dirigir a cartelera (CLIENTE/EMPLEADO)
        this.cartelera(this.pelicula);
    }//GEN-LAST:event_getPeliculaMaincraft

    private void getPeliculaKarateKid(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPeliculaKarateKid
        //Titulo de la pelicula
        this.pelicula.SeleccionarTituloPelicula(4);
        //Genero de la pelicula
        this.pelicula.SeleccionarGeneroPelicula(4);
        //Duracion de la pelicula
        this.pelicula.SeleccionarDuracionPelicula(4);
        // Dirigir a cartelera (CLIENTE/EMPLEADO)
        this.cartelera(this.pelicula);
    }//GEN-LAST:event_getPeliculaKarateKid


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getPelicula1;
    private javax.swing.JButton getPelicula2;
    private javax.swing.JButton getPelicula3;
    private javax.swing.JButton getPelicula4;
    private javax.swing.JButton getPelicula5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
