package GUI;

import Clases.Empleado;
import Clases.Pago;
import Clases.Pelicula;
import Clases.Pilas;
import Clases.Sala;
import javax.swing.JOptionPane;


public class RealizarPago_Empleado extends javax.swing.JFrame {

    private Pago pago;
    private Pelicula pelicula;
    private Sala sala;
    String metodoPago = "";
    private Empleado empleado;
    private final ConfirmacionCompra compraConfirmar;
    private Pilas pila;
    
    public void setPila(Pilas pila) {
        this.pila = pila;
    }

    public RealizarPago_Empleado() {
        initComponents();
        this.compraConfirmar = new ConfirmacionCompra();
        this.empleado = new Empleado();
    }

    public void iniciar(Pago pago, Pelicula pelicula, Sala sala) {
        this.pago = pago;
        this.pelicula = pelicula;
        this.sala = sala;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        this.getMontoPago.setText("S/" + String.format("%.2f", this.pago.getMonto()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MetodoPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        getMontoPago = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        getMetodoPago1 = new javax.swing.JRadioButton();
        getMetodoPago2 = new javax.swing.JRadioButton();
        getMetodoPago3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realizar tu pago");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Monto total:");

        getMontoPago.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getMontoPago.setForeground(new java.awt.Color(255, 0, 51));
        getMontoPago.setText("S/15.00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("ELIGE TU METODO DE PAGO");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("CONFIRMAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarPago(evt);
            }
        });

        MetodoPago.add(getMetodoPago1);
        getMetodoPago1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getMetodoPago1.setText("Efectivo");

        MetodoPago.add(getMetodoPago2);
        getMetodoPago2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getMetodoPago2.setText("Tarjeta");

        MetodoPago.add(getMetodoPago3);
        getMetodoPago3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getMetodoPago3.setText("Yape/Plin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(getMetodoPago1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(70, 70, 70))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(getMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 30, Short.MAX_VALUE))))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getMetodoPago3)
                            .addComponent(getMetodoPago2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(getMetodoPago1)
                .addGap(20, 20, 20)
                .addComponent(getMetodoPago2)
                .addGap(20, 20, 20)
                .addComponent(getMetodoPago3)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ElegirMetodoPago() {

        if (this.getMetodoPago1.isSelected()) {
            this.metodoPago = "Efectivo";
        } else if (this.getMetodoPago2.isSelected()) {
            this.metodoPago = "Tarjeta";
        } else if (this.getMetodoPago3.isSelected()) {
            this.metodoPago = "Yape/Plin";
        }
    }

    private void BotonConfirmarPago(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarPago
        // Elegir metodo de pago
        this.ElegirMetodoPago();

        if (this.metodoPago.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor!, Elegir un metodo de pago");
        } else {
            this.pago.setMetodoPago(this.metodoPago);
            this.empleado.setPago(pago);
            this.compraConfirmar.iniciar(this.pelicula, this.sala);
            this.setVisible(false);
        }

    }//GEN-LAST:event_BotonConfirmarPago


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup MetodoPago;
    private javax.swing.JRadioButton getMetodoPago1;
    private javax.swing.JRadioButton getMetodoPago2;
    private javax.swing.JRadioButton getMetodoPago3;
    private javax.swing.JLabel getMontoPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
