package GUI;

import Clases.Empleado;
import Clases.Pago;
import Clases.Pelicula;
import Clases.Pilas;
import Clases.Sala;
import javax.swing.JOptionPane;


public class RealizarPago_Cliente extends javax.swing.JFrame {

    private Pago pago;
    private Pelicula pelicula;
    private Sala sala;
    private final Empleado empleado;
    private final ConfirmacionCompra compraConfirmar;
    String metodoPago = "";
    private Pilas pila;
    
    public void setPila(Pilas pila) {
        this.pila = pila;
    }
    
    public RealizarPago_Cliente() {
        initComponents();
        this.compraConfirmar = new ConfirmacionCompra();
        this.empleado = new Empleado();
    }
    
    public void iniciar(Pago pago,Pelicula pelicula,Sala sala){
        this.pago = pago;
        this.pelicula = pelicula;
        this.sala = sala;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.getMontoPago.setText("S/"+String.format("%.2f",this.pago.getMonto()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        getMontoPago = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        getDig1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        getfechaTarjeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        getCVVTarjeta = new javax.swing.JTextField();
        BotonConfirmar = new javax.swing.JButton();
        getDig2 = new javax.swing.JTextField();
        getDig3 = new javax.swing.JTextField();
        getDig4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realizar tu pago");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Monto total:");

        getMontoPago.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getMontoPago.setForeground(new java.awt.Color(255, 0, 51));
        getMontoPago.setText("S/15.00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("NRO Tarjeta:");

        getDig1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getDig1.setForeground(new java.awt.Color(0, 51, 255));
        getDig1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                getDig1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Fecha de Vencimiento:");

        getfechaTarjeta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getfechaTarjeta.setForeground(new java.awt.Color(0, 51, 255));
        getfechaTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                getfechaTarjetaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("CVV:");

        getCVVTarjeta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getCVVTarjeta.setForeground(new java.awt.Color(0, 51, 255));
        getCVVTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                getCVVTarjetaKeyTyped(evt);
            }
        });

        BotonConfirmar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonConfirmar.setText("CONFIRMAR");
        BotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarPago(evt);
            }
        });

        getDig2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getDig2.setForeground(new java.awt.Color(0, 51, 255));
        getDig2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                getDig2KeyTyped(evt);
            }
        });

        getDig3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getDig3.setForeground(new java.awt.Color(0, 51, 255));
        getDig3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                getDig3KeyTyped(evt);
            }
        });

        getDig4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getDig4.setForeground(new java.awt.Color(0, 51, 255));
        getDig4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                getDig4KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(getCVVTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(getMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(getfechaTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(getDig1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(getDig2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(getDig3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(getDig4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDig1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDig2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDig3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDig4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getfechaTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getCVVTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConfirmarPago(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarPago
        // recoger variables
        String numeroTarjeta = this.getDig1.getText()+"-"+this.getDig2.getText()+"-"+this.getDig3.getText()+"-"+this.getDig4.getText();
        String fecha = this.getfechaTarjeta.getText();
        String cvv = this.getCVVTarjeta.getText();
        
        
        
        if(numeroTarjeta.equals("") || numeroTarjeta.equals("") || numeroTarjeta.equals("")){
            JOptionPane.showMessageDialog(null,"Por favor!, ingrese los datos");
        }else{
            this.pago.setNumeroTarjeta(numeroTarjeta);
            this.pago.setFecha(fecha);
            this.pago.setCvv(cvv);
            
            this.metodoPago = "Efectivo";
            this.pago.setMetodoPago(this.metodoPago);
            this.empleado.setPago(pago);
            this.compraConfirmar.iniciar(this.pelicula,this.sala);
            compraConfirmar.setPila(pila);
            this.setVisible(false);
            
        }
        
    }//GEN-LAST:event_BotonConfirmarPago

    private void getDig1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getDig1KeyTyped
        if(this.getDig1.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_getDig1KeyTyped

    private void getDig2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getDig2KeyTyped
        if(this.getDig2.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_getDig2KeyTyped

    private void getDig3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getDig3KeyTyped
        if(this.getDig3.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_getDig3KeyTyped

    private void getDig4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getDig4KeyTyped
        if(this.getDig4.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_getDig4KeyTyped

    private void getCVVTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getCVVTarjetaKeyTyped
        if(this.getCVVTarjeta.getText().length()>=3){
            evt.consume();
        }
    }//GEN-LAST:event_getCVVTarjetaKeyTyped

    private void getfechaTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getfechaTarjetaKeyTyped
        if(this.getfechaTarjeta.getText().length()>=5){
            evt.consume();
        }
    }//GEN-LAST:event_getfechaTarjetaKeyTyped

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConfirmar;
    private javax.swing.JTextField getCVVTarjeta;
    private javax.swing.JTextField getDig1;
    private javax.swing.JTextField getDig2;
    private javax.swing.JTextField getDig3;
    private javax.swing.JTextField getDig4;
    private javax.swing.JLabel getMontoPago;
    private javax.swing.JTextField getfechaTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
