package GUI;

import Clases.Cola;
import Clases.Pago;
import Clases.Pelicula;
import Clases.Pilas;
import Clases.Sala;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

public class Tarifario_Cliente extends javax.swing.JFrame {

    private final SpinnerNumberModel spinner_1, spinner_2, spinner_3;
    private final SeleccionarAsiento seleccionarAsiento;
    private Pelicula pelicula;
    private Sala sala;
    private Cola colaClientes = new Cola(10);
    private Pilas pila;
    
    public void setPila(Pilas pila) {
        this.pila = pila;
    }
    public Tarifario_Cliente() {
        initComponents();
        this.seleccionarAsiento = new SeleccionarAsiento();
        this.spinner_1 = new SpinnerNumberModel();
        this.spinner_2 = new SpinnerNumberModel();
        this.spinner_3 = new SpinnerNumberModel();
        
        // Configuración inicial de los spinners (límites)
        // Spinner para Adultos
        this.spinner_1.setMinimum(0);
        this.spinner_1.setMaximum(25); // Límite individual, la suma se valida luego
        this.cantidadAdulto.setModel(this.spinner_1);

        // Spinner para Adulto Mayor
        this.spinner_2.setMinimum(0);
        this.spinner_2.setMaximum(25);
        this.cantidadAdultoMayor.setModel(this.spinner_2);

        // Spinner para Infantil
        this.spinner_3.setMinimum(0);
        this.spinner_3.setMaximum(25);
        this.cantidadInfantil.setModel(this.spinner_3);
    }

    public void iniciar(Pelicula pelicula,Sala sala) {
        this.pelicula = pelicula;
        this.sala = sala;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Tarifario - Cliente");
        
         // Resetear los valores de los spinners a 0 cada vez que se muestra la ventana
        this.spinner_1.setValue(0);
        this.spinner_2.setValue(0);
        this.spinner_3.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cantidadAdulto = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cantidadInfantil = new javax.swing.JSpinner();
        cantidadAdultoMayor = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TARIFARIO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TIPO DE ENTRADA:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Adulto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("S/15");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");

        cantidadAdulto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Infantil 2 - 8");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("S/12");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Adulto Mayor +60");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("S/12");

        cantidadInfantil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cantidadAdultoMayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTarifaCliente(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantidadInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantidadAdultoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(cantidadAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadAdultoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTarifaCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTarifaCliente
        int cantidadEntradaAdulto = ((Number) this.cantidadAdulto.getValue()).intValue();
        int cantidadEntradaInfantil = ((Number) this.cantidadInfantil.getValue()).intValue(); 
        int cantidadEntradaAdultoMayor = ((Number) this.cantidadAdultoMayor.getValue()).intValue(); 

        int totalEntradasSeleccionadas = cantidadEntradaAdulto + cantidadEntradaInfantil + cantidadEntradaAdultoMayor;

        if (totalEntradasSeleccionadas == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos una entrada.", "Selección Requerida", JOptionPane.WARNING_MESSAGE);
            return; 
        }

        int maxAsientosSala = 25; 
        if (totalEntradasSeleccionadas > maxAsientosSala) {
            JOptionPane.showMessageDialog(this,
                    "La cantidad total de entradas (" + totalEntradasSeleccionadas + ") excede el máximo de asientos disponibles en la sala (" + maxAsientosSala + ").\nPor favor, ajuste la cantidad.",
                    "Límite de Capacidad Excedido",
                    JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        //Este código simula la espera en un cine: asigna un turno aleatorio (1-10) y muestra cómo atienden a 
        //cada cliente anterior con mensajes cada 1 segundos. Al final, avisa cuando es tu turno, recreando la experiencia real de hacer fila.
        int numeroCliente = (int)(Math.random() * 10 + 1);
        JOptionPane.showMessageDialog(this, "Te tocó el número " + numeroCliente + " en el sorteo. Espera tu turno...");
        colaClientes.llenarCola();

        try {
            for (int i = 1; i < numeroCliente; i++) {
                int atendido = colaClientes.eliminarCliente();

                JOptionPane.showMessageDialog(
                    this,
                    "Se atendió al cliente número " + atendido + "...",
                    "Atendiendo...",
                    JOptionPane.INFORMATION_MESSAGE
                );

                Thread.sleep(1000);
            }

        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }

        JOptionPane.showMessageDialog(this, "¡Ahora es tu turno, cliente #" + numeroCliente + "!");

        // Cálculo de precios
        double precioAdulto = cantidadEntradaAdulto * 15.0; 
        double precioInfantil = cantidadEntradaInfantil * 12.0;
        double precioAdultoMayor = cantidadEntradaAdultoMayor * 12.0;
        double totalAPagar = precioAdulto + precioInfantil + precioAdultoMayor;

        Pago pago = new Pago();
        pago.setMonto(totalAPagar);

        // Ir a la ventana de selección de asientos
        this.seleccionarAsiento.iniciar(0, pago, this.pelicula, this.sala, totalEntradasSeleccionadas); 
        this.setVisible(false);  
    }//GEN-LAST:event_BotonTarifaCliente


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cantidadAdulto;
    private javax.swing.JSpinner cantidadAdultoMayor;
    private javax.swing.JSpinner cantidadInfantil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
