package GUI;

import Clases.Pago;
import Clases.Pelicula;
import Clases.Pilas;
import Clases.Sala;
import javax.swing.SpinnerNumberModel;


public class Tarifario_Empleado extends javax.swing.JFrame {

    private Cartelera cartelera;
    private Pelicula pelicula;
    private final Sala sala;
    private final SpinnerNumberModel spinner_1, spinner_2, spinner_3;
    private final SeleccionarAsiento seleccionarAsiento;
    private Pilas pila;
    
    public void setPila(Pilas pila) {
        this.pila = pila;
    }
    
    public Tarifario_Empleado() {
        initComponents();
        this.seleccionarAsiento = new SeleccionarAsiento();
        this.sala = new Sala();
        
        this.spinner_1 = new SpinnerNumberModel();
        this.spinner_2 = new SpinnerNumberModel();
        this.spinner_3 = new SpinnerNumberModel();
    }
    
    public void iniciar(Cartelera cartelera,Pelicula pelicula){
        this.cartelera = cartelera;
        this.pelicula = pelicula;
        this.cartelera.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        /*Spinner_1*/
        this.spinner_1.setMaximum(100);
        this.spinner_1.setMinimum(0);
        /*Spinner_2*/
        this.spinner_2.setMaximum(100);
        this.spinner_2.setMinimum(0);
        /*Spinner_3*/
        this.spinner_3.setMaximum(100);
        this.spinner_3.setMinimum(0);

        this.cantidadAdulto.setModel(this.spinner_1);
        this.cantidadAdultoMayor.setModel(this.spinner_2);
        this.cantidadInfantil.setModel(this.spinner_3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Horarios = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cantidadAdulto = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cantidadInfantil = new javax.swing.JSpinner();
        cantidadAdultoMayor = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        opcHorario1 = new javax.swing.JRadioButton();
        opcHorario2 = new javax.swing.JRadioButton();
        opcHorario3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TARIFARIO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TIPO DE ENTRADA:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Adulto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("S/15");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");

        cantidadAdulto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Infantil 2 - 8");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("S/12");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Adulto Mayor +60");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("S/12");

        cantidadInfantil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cantidadAdultoMayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTarifaEmpleado(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Selección de horarios");

        Horarios.add(opcHorario1);
        opcHorario1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opcHorario1.setText("8:00 pm");
        opcHorario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcHorario1ActionPerformed(evt);
            }
        });

        Horarios.add(opcHorario2);
        opcHorario2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opcHorario2.setText("6:00 pm");
        opcHorario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcHorario2ActionPerformed(evt);
            }
        });

        Horarios.add(opcHorario3);
        opcHorario3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opcHorario3.setText("4:00 pm");
        opcHorario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcHorario3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cantidadAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantidadInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantidadAdultoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(opcHorario1)
                                .addGap(50, 50, 50)
                                .addComponent(opcHorario2)
                                .addGap(50, 50, 50)
                                .addComponent(opcHorario3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadAdultoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcHorario1)
                    .addComponent(opcHorario2)
                    .addComponent(opcHorario3))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void SeleccionarHorario() {
        String horario = "";
        if (this.opcHorario1.isSelected()) {
            horario = "8:00 pm";
        } else if (this.opcHorario2.isSelected()) {
            horario = "6:00 pm";
        } else if (this.opcHorario3.isSelected()) {
            horario = "4:00 pm";
        }
        this.sala.setHorario(horario);
    }
    
    private void opcHorario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcHorario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcHorario1ActionPerformed

    private void opcHorario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcHorario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcHorario2ActionPerformed

    private void opcHorario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcHorario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcHorario3ActionPerformed

    private void BotonTarifaEmpleado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTarifaEmpleado
        double entradaAdulto = ((Number) this.cantidadAdulto.getValue()).doubleValue();
        double entradaInfantil = ((Number) this.cantidadInfantil.getValue()).doubleValue();
        double entradaAdultoMayor = ((Number) this.cantidadAdultoMayor.getValue()).doubleValue();

        double precioAdulto = entradaAdulto * 15;
        double precioInfantil = entradaInfantil * 12;
        double precioAdultoMayor = entradaAdultoMayor * 12;

        double total = precioAdulto + precioInfantil + precioAdultoMayor;
        
        this.SeleccionarHorario();
        
        double var = entradaAdulto + entradaInfantil + entradaAdultoMayor;
        Pago pago = new Pago();
        pago.setMonto(total);
        
        //Ventana Seleccionar Asiento
        this.seleccionarAsiento.iniciar(1,pago,this.pelicula,this.sala, (int) var);//indice empleado:1
        this.setVisible(false);
    }//GEN-LAST:event_BotonTarifaEmpleado

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Horarios;
    private javax.swing.JSpinner cantidadAdulto;
    private javax.swing.JSpinner cantidadAdultoMayor;
    private javax.swing.JSpinner cantidadInfantil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton opcHorario1;
    private javax.swing.JRadioButton opcHorario2;
    private javax.swing.JRadioButton opcHorario3;
    // End of variables declaration//GEN-END:variables
}
